version: '3'
services:
  db:
    image: mariadb:10.10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: presta
      MARIADB_ROOT_HOST: '%'
      MARIADB_USER: user
      MARIADB_PASSWORD: admin
    networks:
      - presta_network
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - presta_network
   
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      # PS_INSTALL_DB: 1
      # PS_INSTALL_AUTO: 1
      # PS_DEMO_MODE: 1
      DB_SERVER: db
      DB_NAME: presta
      DB_USER: root
      DB_PASSWD: admin
      PS_DOMAIN: localhost:8080
      PS_LANGUAGE: pl
      PS_COUNTRY: PL
      ADMIN_MAIL: demo@prestashop.com
      ADMIN_PASSWD: prestashop_demo
    networks:
      - presta_network
    volumes:
      # - type: bind
        # source: ./modules/testModule # local path to the module
        # target: /var/www/html/modules/testModule # path to be mounted in the container
      # - type: bind
        # source: ./themes/myTheme # local path to the theme
        # target:  /var/www/html/themes/myTheme # path to be mounted in the container
      - psdata:/var/www/html

networks:
  presta_network:
volumes:
  psdata:
  dbdata: